import {
    Clinic,
    Donor,
    TransfusionRequest,
    BloodUnit,
    DEAStatus,
    ComponentType,
    UrgencyLevel,
    ConsentStatus,
} from '../types/types';

export const mockClinics: Clinic[] = [
    {
        id: 'clinic-1',
        name: 'Metro Emergency Center',
        location: { lat: 13.0827, lng: 80.2707 },
        inventory: {
            WB: 4,
            pRBC: 7,
        },
        ageDistribution: {
            days0to7: 5,
            days8to14: 4,
            days15to21: 2,
        },
        expiringUnits: {
            count: 2,
            daysUntilExpiry: 2,
        },
    },
    {
        id: 'clinic-2',
        name: 'Northside Animal Hospital',
        location: { lat: 13.1027, lng: 80.2507 },
        inventory: {
            WB: 2,
            pRBC: 5,
        },
        ageDistribution: {
            days0to7: 3,
            days8to14: 3,
            days15to21: 1,
        },
        expiringUnits: {
            count: 1,
            daysUntilExpiry: 4,
        },
    },
    {
        id: 'clinic-3',
        name: 'University Veterinary Clinic',
        location: { lat: 13.0627, lng: 80.2907 },
        inventory: {
            WB: 8,
            pRBC: 3,
        },
        ageDistribution: {
            days0to7: 6,
            days8to14: 3,
            days15to21: 2,
        },
        expiringUnits: {
            count: 0,
            daysUntilExpiry: 7,
        },
    },
    {
        id: 'clinic-4',
        name: 'Regional Blood Bank',
        location: { lat: 13.0427, lng: 80.2607 },
        inventory: {
            WB: 12,
            pRBC: 15,
        },
        ageDistribution: {
            days0to7: 15,
            days8to14: 8,
            days15to21: 4,
        },
        expiringUnits: {
            count: 3,
            daysUntilExpiry: 1,
        },
    },
];

export const mockDonors: Donor[] = [
    {
        id: 'D-2847',
        signalment: { breed: 'Golden Retriever', weight: 28, age: 5 },
        deaStatus: DEAStatus.POSITIVE,
        donationHistory: { monthsSinceLastDonation: 4 },
        lifetimeDonations: 8,
        ownerConsent: ConsentStatus.CURRENT,
        welfareConstraints: { screening: true, behavioral: true, veterinary: true },
        isEligible: true,
    },
    {
        id: 'D-3192',
        signalment: { breed: 'Labrador Retriever', weight: 32, age: 4 },
        deaStatus: DEAStatus.NEGATIVE,
        donationHistory: { monthsSinceLastDonation: 2 },
        lifetimeDonations: 5,
        ownerConsent: ConsentStatus.CURRENT,
        welfareConstraints: { screening: true, behavioral: true, veterinary: true },
        isEligible: false,
        ineligibilityReason: 'Below minimum 3-month interval',
    },
    {
        id: 'D-4521',
        signalment: { breed: 'German Shepherd', weight: 35, age: 6 },
        deaStatus: DEAStatus.NEGATIVE,
        donationHistory: { monthsSinceLastDonation: 6 },
        lifetimeDonations: 12,
        ownerConsent: ConsentStatus.CURRENT,
        welfareConstraints: { screening: true, behavioral: true, veterinary: true },
        isEligible: true,
    },
    {
        id: 'D-1834',
        signalment: { breed: 'Rottweiler', weight: 40, age: 3 },
        deaStatus: DEAStatus.POSITIVE,
        donationHistory: { monthsSinceLastDonation: 5 },
        lifetimeDonations: 6,
        ownerConsent: ConsentStatus.CURRENT,
        welfareConstraints: { screening: true, behavioral: false, veterinary: true },
        isEligible: false,
        ineligibilityReason: 'Behavioral assessment unsuitable',
    },
    {
        id: 'D-5672',
        signalment: { breed: 'Doberman', weight: 30, age: 4 },
        deaStatus: DEAStatus.UNKNOWN,
        donationHistory: { monthsSinceLastDonation: 8 },
        lifetimeDonations: 4,
        ownerConsent: ConsentStatus.PENDING,
        welfareConstraints: { screening: true, behavioral: true, veterinary: true },
        isEligible: false,
        ineligibilityReason: 'Owner consent pending',
    },
    {
        id: 'D-7823',
        signalment: { breed: 'Great Dane', weight: 45, age: 5 },
        deaStatus: DEAStatus.NEGATIVE,
        donationHistory: { monthsSinceLastDonation: 12 },
        lifetimeDonations: 10,
        ownerConsent: ConsentStatus.CURRENT,
        welfareConstraints: { screening: true, behavioral: true, veterinary: true },
        isEligible: true,
    },
    {
        id: 'D-2156',
        signalment: { breed: 'Boxer', weight: 27, age: 7 },
        deaStatus: DEAStatus.POSITIVE,
        donationHistory: { monthsSinceLastDonation: 1 },
        lifetimeDonations: 15,
        ownerConsent: ConsentStatus.CURRENT,
        welfareConstraints: { screening: false, behavioral: true, veterinary: true },
        isEligible: false,
        ineligibilityReason: 'Screening expired',
    },
    {
        id: 'D-9341',
        signalment: { breed: 'Belgian Malinois', weight: 29, age: 4 },
        deaStatus: DEAStatus.NEGATIVE,
        donationHistory: { monthsSinceLastDonation: 7 },
        lifetimeDonations: 9,
        ownerConsent: ConsentStatus.CURRENT,
        welfareConstraints: { screening: true, behavioral: true, veterinary: true },
        isEligible: true,
    },
    {
        id: 'D-4782',
        signalment: { breed: 'Bernese Mountain Dog', weight: 38, age: 5 },
        deaStatus: DEAStatus.POSITIVE,
        donationHistory: { monthsSinceLastDonation: 10 },
        lifetimeDonations: 7,
        ownerConsent: ConsentStatus.WITHDRAWN,
        welfareConstraints: { screening: true, behavioral: true, veterinary: true },
        isEligible: false,
        ineligibilityReason: 'Owner consent withdrawn',
    },
    {
        id: 'D-6129',
        signalment: { breed: 'Irish Setter', weight: 26, age: 3 },
        deaStatus: DEAStatus.NEGATIVE,
        donationHistory: { monthsSinceLastDonation: 5 },
        lifetimeDonations: 3,
        ownerConsent: ConsentStatus.CURRENT,
        welfareConstraints: { screening: true, behavioral: true, veterinary: false },
        isEligible: false,
        ineligibilityReason: 'Veterinary clearance needed',
    },
];

export const mockRequests: TransfusionRequest[] = [
    {
        id: 'REQ-001',
        patientId: 'P-8472',
        componentType: ComponentType.PRBC,
        requiredDEAStatus: DEAStatus.NEGATIVE,
        urgencyLevel: UrgencyLevel.URGENT,
    },
    {
        id: 'REQ-002',
        patientId: 'P-3291',
        componentType: ComponentType.WB,
        requiredDEAStatus: DEAStatus.POSITIVE,
        urgencyLevel: UrgencyLevel.ROUTINE,
    },
];

export const mockBloodUnits: BloodUnit[] = [
    {
        id: 'U-4729',
        sourceClinic: 'Regional Blood Bank',
        transportTime: 23,
        collectionDate: '2024-03-10',
        storageLocation: 'Refrigerator B-3',
        deaStatus: DEAStatus.NEGATIVE,
        componentType: ComponentType.PRBC,
        isCompatible: true,
        compatibilityNote: 'Compatible: DEA 1.1 Negative Universal Donor',
    },
    {
        id: 'U-5821',
        sourceClinic: 'Metro Emergency Center',
        transportTime: 5,
        collectionDate: '2024-03-12',
        storageLocation: 'Refrigerator A-1',
        deaStatus: DEAStatus.POSITIVE,
        componentType: ComponentType.PRBC,
        isCompatible: false,
        compatibilityNote: 'Caution: DEA 1.1 Positive—verify recipient status',
    },
    {
        id: 'U-3147',
        sourceClinic: 'University Veterinary Clinic',
        transportTime: 18,
        collectionDate: '2024-03-11',
        storageLocation: 'Refrigerator C-2',
        deaStatus: DEAStatus.NEGATIVE,
        componentType: ComponentType.PRBC,
        isCompatible: true,
        compatibilityNote: 'Compatible: DEA 1.1 Negative Universal Donor',
    },
    {
        id: 'U-7293',
        sourceClinic: 'Northside Animal Hospital',
        transportTime: 12,
        collectionDate: '2024-03-09',
        storageLocation: 'Refrigerator D-1',
        deaStatus: DEAStatus.NEGATIVE,
        componentType: ComponentType.WB,
        isCompatible: true,
        compatibilityNote: 'Compatible: DEA 1.1 Negative Universal Donor',
    },
    {
        id: 'U-8456',
        sourceClinic: 'Regional Blood Bank',
        transportTime: 25,
        collectionDate: '2024-03-13',
        storageLocation: 'Refrigerator B-5',
        deaStatus: DEAStatus.NEGATIVE,
        componentType: ComponentType.PRBC,
        isCompatible: true,
        compatibilityNote: 'Compatible: DEA 1.1 Negative Universal Donor',
    },
    {
        id: 'U-2918',
        sourceClinic: 'Metro Emergency Center',
        transportTime: 7,
        collectionDate: '2024-03-14',
        storageLocation: 'Refrigerator A-3',
        deaStatus: DEAStatus.POSITIVE,
        componentType: ComponentType.WB,
        isCompatible: false,
        compatibilityNote: 'Caution: DEA 1.1 Positive—verify recipient status',
    },
];
